version: '3.8'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-hr_db}
      MYSQL_USER: ${MYSQL_USER:-hr_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-iav@2025}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-iav@2025}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:7
    command: ["redis-server", "--save", "", "--appendonly", "no"]

  web:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DEBUG: ${DEBUG:-True}
      SECRET_KEY: ${SECRET_KEY:-dev-secret}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-hr_db}
      MYSQL_USER: ${MYSQL_USER:-hr_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-iav@2025}
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL:-redis://redis:6379/1}
    depends_on:
      - db
      - redis

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: iav@2025
      MYSQL_ROOT_PASSWORD: iav@2025
    ports:
      - "8080:80"
    depends_on:
      - db

  # Celery worker can be enabled later once Celery is configured in the project
  # celery:
  #   build: .
  #   command: celery -A hr_project worker -l info
  #   volumes:
  #     - .:/app
  #   environment:
  #     - CELERY_BROKER_URL=${CELERY_BROKER_URL}
  #     - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
  #   depends_on:
  #     - redis
  #     - db

volumes:
  mysql_data:
