# Generated by Django 5.2.7 on 2025-10-29 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('fingerprint_reader', 'Fingerprint Reader'), ('usb_signature_pad', 'USB Signature Pad'), ('face_camera', 'Face Recognition Camera'), ('iris_scanner', 'Iris Scanner')], help_text='Type of biometric device', max_length=50)),
                ('device_name', models.CharField(help_text='Device name/model', max_length=200)),
                ('device_serial', models.CharField(help_text='Device serial number or unique ID', max_length=100, unique=True)),
                ('device_fingerprint', models.CharField(help_text='Device hardware fingerprint for verification', max_length=256)),
                ('enrollment_data', models.TextField(blank=True, help_text='Encrypted biometric enrollment template')),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Device has been verified by admin')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('failed_attempts', models.IntegerField(default=0, help_text='Number of failed authentication attempts')),
                ('locked_until', models.DateTimeField(blank=True, help_text='Device locked until this time due to failed attempts', null=True)),
            ],
            options={
                'verbose_name': 'Biometric Device',
                'verbose_name_plural': 'Biometric Devices',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='electronicsignature',
            new_name='signatures__content_a7c899_idx',
            old_name='signatures__content_f28d26_idx',
        ),
        migrations.RenameIndex(
            model_name='electronicsignature',
            new_name='signatures__signer__692e6a_idx',
            old_name='signatures__signer__03c1b7_idx',
        ),
        migrations.RenameIndex(
            model_name='electronicsignature',
            new_name='signatures__status_a34de8_idx',
            old_name='signatures__status_43e3f7_idx',
        ),
        migrations.AddField(
            model_name='electronicsignature',
            name='biometric_data',
            field=models.TextField(blank=True, help_text='Fingerprint or biometric data (encrypted)'),
        ),
        migrations.AddField(
            model_name='electronicsignature',
            name='biometric_type',
            field=models.CharField(blank=True, choices=[('fingerprint', 'Fingerprint'), ('face', 'Face Recognition'), ('iris', 'Iris Scan')], help_text='Type of biometric authentication used', max_length=50),
        ),
        migrations.AddField(
            model_name='electronicsignature',
            name='signature_method',
            field=models.CharField(choices=[('drawn', 'Drawn on Canvas'), ('typed', 'Typed Name'), ('usb_device', 'USB Signature Device'), ('biometric', 'Biometric (Fingerprint)')], default='drawn', help_text='Method used to capture the signature', max_length=20),
        ),
        migrations.AddField(
            model_name='electronicsignature',
            name='usb_device_data',
            field=models.TextField(blank=True, help_text='Signature data from USB device (encrypted)'),
        ),
        migrations.AddField(
            model_name='electronicsignature',
            name='usb_device_serial',
            field=models.CharField(blank=True, help_text='USB signature device serial number', max_length=100),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='user',
            field=models.ForeignKey(help_text='User who owns this device', on_delete=django.db.models.deletion.CASCADE, related_name='biometric_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='biometricdevice',
            index=models.Index(fields=['user', 'is_active'], name='signatures__user_id_0a6197_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricdevice',
            index=models.Index(fields=['device_serial'], name='signatures__device__796343_idx'),
        ),
    ]
