# Generated by Django 5.2.7 on 2025-10-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0002_biometricdevice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricdevice',
            name='stamp_image_path',
            field=models.CharField(blank=True, help_text='Encrypted path to stamp image on USB device', max_length=500),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='stamp_image_preview',
            field=models.TextField(blank=True, help_text='Base64 preview of stamp image (watermarked)'),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='stamp_password_hash',
            field=models.CharField(blank=True, help_text='Hashed password for USB stamp verification', max_length=256),
        ),
        migrations.AddField(
            model_name='electronicsignature',
            name='usb_stamp_image',
            field=models.TextField(blank=True, help_text='Base64 encoded stamp image from USB (official company seal)'),
        ),
        migrations.AddField(
            model_name='electronicsignature',
            name='usb_stamp_serial',
            field=models.CharField(blank=True, help_text='USB device serial containing the stamp', max_length=100),
        ),
        migrations.AddField(
            model_name='electronicsignature',
            name='usb_stamp_verified',
            field=models.BooleanField(default=False, help_text='Password verification successful for USB stamp'),
        ),
        migrations.AlterField(
            model_name='biometricdevice',
            name='device_type',
            field=models.CharField(choices=[('fingerprint_reader', 'Fingerprint Reader'), ('usb_signature_pad', 'USB Signature Pad'), ('usb_stamp_device', 'USB Digital Stamp Device (Password Protected)'), ('face_camera', 'Face Recognition Camera'), ('iris_scanner', 'Iris Scanner')], help_text='Type of biometric device', max_length=50),
        ),
        migrations.AlterField(
            model_name='electronicsignature',
            name='signature_method',
            field=models.CharField(choices=[('drawn', 'Drawn on Canvas'), ('typed', 'Typed Name'), ('usb_device', 'USB Signature Device'), ('biometric', 'Biometric (Fingerprint)'), ('usb_stamp', 'USB Digital Stamp (Password Protected)')], default='drawn', help_text='Method used to capture the signature', max_length=20),
        ),
    ]
