# Generated by Django 5.2.7 on 2025-10-29 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0003_biometricdevice_stamp_image_path_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StampArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.BigIntegerField(default=0)),
                ('ciphertext', models.BinaryField()),
                ('nonce', models.BinaryField()),
                ('sha256_hash', models.CharField(max_length=64)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stamp_artifacts', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='User who uploaded the stamp artifact', on_delete=django.db.models.deletion.CASCADE, related_name='stamp_artifacts', to=settings.AUTH_USER_MODEL)),
                ('related_device', models.ForeignKey(blank=True, help_text='Optional device linked to this artifact', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stamp_artifacts', to='signatures.biometricdevice')),
            ],
            options={
                'verbose_name': 'Stamp Artifact',
                'verbose_name_plural': 'Stamp Artifacts',
                'ordering': ['-uploaded_at'],
                'indexes': [
                    models.Index(fields=['owner', 'is_approved'], name='signatures__owner_i_1a2b3c'),
                ],
            },
        ),
        migrations.AddField(
            model_name='electronicsignature',
            name='stamp_artifact',
            field=models.ForeignKey(blank=True, help_text='Approved encrypted stamp artifact used at signing time', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to='signatures.stampartifact'),
        ),
        migrations.AddField(
            model_name='electronicsignature',
            name='artifact_integrity_hash',
            field=models.CharField(blank=True, help_text='SHA256 of plaintext artifact at time of signing for integrity verification', max_length=64),
        ),
    ]
