# Generated by Django 5.2.7 on 2025-10-29 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0004_stampartifact_electronicsignature_stamp_artifact_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stampartifact',
            new_name='signatures__owner_i_f14466_idx',
            old_name='signatures__owner_i_1a2b3c',
        ),
    ]
