# Generated by Django 5.2.7 on 2025-10-25 14:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Direction',
                'verbose_name_plural': 'Directions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('cadre_superieur', 'Cadre Supérieur'), ('cadre', 'Cadre'), ('maitrise', 'Maîtrise'), ('execution', 'Exécution')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('position_type', models.CharField(choices=[('chef_direction', 'Chef de Direction'), ('chef_division', 'Chef de Division'), ('chef_service', 'Chef de Service'), ('employee', 'Employé')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['position_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='divisions', to='employees.direction')),
            ],
            options={
                'verbose_name': 'Division',
                'verbose_name_plural': 'Divisions',
                'ordering': ['direction', 'name'],
                'unique_together': {('direction', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='employees.division')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['division', 'name'],
                'unique_together': {('division', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('cin', models.CharField(max_length=20, unique=True, verbose_name='CIN')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?212[0-9]{9}$|^0[0-9]{9}$', 'Format: 0612345678 ou +212612345678')], verbose_name='Téléphone')),
                ('date_of_birth', models.DateField(verbose_name='Date de naissance')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('employee_id', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Matricule')),
                ('ppr', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='PPR')),
                ('echelle', models.IntegerField(blank=True, help_text='Échelle de 1 à 11', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)], verbose_name='Échelle')),
                ('hors_echelle', models.BooleanField(default=False, verbose_name='Hors Échelle')),
                ('echelon', models.IntegerField(blank=True, help_text='Échelon de 1 à 10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Échelon')),
                ('contract_type', models.CharField(choices=[('titulaire', 'Titulaire'), ('contractuel', 'Contractuel'), ('stagiaire', 'Stagiaire'), ('detache', 'Détaché')], default='titulaire', max_length=20, verbose_name='Type de contrat')),
                ('hire_date', models.DateField(verbose_name='Date de recrutement')),
                ('contract_start_date', models.DateField(blank=True, null=True, verbose_name='Date début contrat')),
                ('contract_end_date', models.DateField(blank=True, null=True, verbose_name='Date fin contrat')),
                ('titularisation_date', models.DateField(blank=True, null=True, verbose_name='Date de titularisation')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('on_leave', 'En Congé'), ('detached', 'Détaché'), ('suspended', 'Suspendu'), ('retired', 'Retraité'), ('inactive', 'Inactif')], default='active', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.direction', verbose_name='Direction')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.division', verbose_name='Division')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.grade', verbose_name='Grade')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.position', verbose_name='Fonction')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['direction', 'status'], name='employees_e_directi_b89c73_idx'), models.Index(fields=['last_name', 'first_name'], name='employees_e_last_na_99a4c0_idx'), models.Index(fields=['grade', 'echelle'], name='employees_e_grade_i_216557_idx')],
            },
        ),
    ]
