# Generated by Django 5.2.7 on 2025-10-25 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_career_progression'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
