# Generated by Django 5.2.7 on 2025-10-27 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_service_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employmenthistory',
            options={'ordering': ['-effective_date', '-created_at'], 'verbose_name': "Historique d'emploi", 'verbose_name_plural': "Historiques d'emploi"},
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date fin contrat'),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date début contrat'),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employment_changes', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='document_reference',
            field=models.CharField(blank=True, max_length=200, verbose_name='Référence document'),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='post_retirement_contract',
            field=models.BooleanField(default=False, verbose_name='Contrat post-retraite'),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='retirement_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de retraite'),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='change_type',
            field=models.CharField(choices=[('grade', 'Changement de Grade'), ('echelle', "Changement d'Échelle"), ('echelon', "Changement d'Échelon"), ('contract', 'Nouveau Contrat'), ('contract_renewal', 'Renouvellement de Contrat'), ('titularisation', 'Titularisation'), ('retirement', 'Retraite'), ('contract_end', 'Fin de Contrat'), ('status', 'Changement de Statut'), ('position', 'Changement de Poste'), ('organization', 'Changement Organisationnel'), ('other', 'Autre')], max_length=20, verbose_name='Type de changement'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='changes',
            field=models.JSONField(default=dict, verbose_name='Détails des changements'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='effective_date',
            field=models.DateField(verbose_name='Date effective'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='note',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
    ]
