# Generated by Django 5.2.7 on 2025-10-28 07:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_position_position_type_departement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='direction',
            index=models.Index(fields=['is_active', 'name'], name='employees_d_is_acti_8c4b0f_idx'),
        ),
        migrations.AddIndex(
            model_name='division',
            index=models.Index(fields=['direction', 'is_active'], name='employees_d_directi_8e26d5_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['division', 'status'], name='employees_e_divisio_06e215_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['service', 'status'], name='employees_e_service_6011b0_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_id'], name='employees_e_employe_514cc5_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['position'], name='employees_e_positio_b2c742_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['direction', 'division', 'service'], name='employees_e_directi_dca75f_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['-created_at'], name='employees_e_created_9cbbc2_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['hire_date'], name='employees_e_hire_da_c2151e_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['division', 'is_active'], name='employees_s_divisio_d02205_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['direction', 'is_active'], name='employees_s_directi_092a74_idx'),
        ),
    ]
