# Generated by Django 5.2.7 on 2025-10-28 08:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employee_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentForfaitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Premier jour du mois concerné', verbose_name='Mois')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant (DH)')),
                ('default_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant par défaut')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Demandé le')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Examiné le')),
                ('review_notes', models.TextField(blank=True, verbose_name="Notes d'examen")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('document_reference', models.CharField(blank=True, max_length=255, verbose_name='Référence document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments_forfaitaire', to='employees.employee', verbose_name='Employé')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment_forfaitaire_requests', to=settings.AUTH_USER_MODEL, verbose_name='Demandé par')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment_forfaitaire_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Examiné par')),
            ],
            options={
                'verbose_name': 'Déplacement forfaitaire',
                'verbose_name_plural': 'Déplacements forfaitaires',
                'ordering': ['-month', '-requested_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='employees_d_employe_9ac936_idx'), models.Index(fields=['month', 'status'], name='employees_d_month_7c1e78_idx'), models.Index(fields=['status', 'requested_at'], name='employees_d_status_1ab8d4_idx')],
                'unique_together': {('employee', 'month')},
            },
        ),
        migrations.CreateModel(
            name='DeploymentReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de départ')),
                ('end_date', models.DateField(verbose_name='Date de retour')),
                ('location', models.CharField(max_length=255, verbose_name='Lieu de mission')),
                ('purpose', models.TextField(verbose_name='Objet de la mission')),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Laisser vide si montant total direct', max_digits=10, null=True, verbose_name='Taux journalier (DH)')),
                ('number_of_days', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de jours')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant total (DH)')),
                ('default_daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Taux journalier par défaut')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Demandé le')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Examiné le')),
                ('review_notes', models.TextField(blank=True, verbose_name="Notes d'examen")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('document_reference', models.CharField(blank=True, max_length=255, verbose_name='Référence document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments_real', to='employees.employee', verbose_name='Employé')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment_real_requests', to=settings.AUTH_USER_MODEL, verbose_name='Demandé par')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment_real_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Examiné par')),
            ],
            options={
                'verbose_name': 'Déplacement réel',
                'verbose_name_plural': 'Déplacements réels',
                'ordering': ['-start_date', '-requested_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='employees_d_employe_515db3_idx'), models.Index(fields=['start_date', 'end_date'], name='employees_d_start_d_a25232_idx'), models.Index(fields=['status', 'requested_at'], name='employees_d_status_10545f_idx')],
            },
        ),
        migrations.CreateModel(
            name='GradeDeploymentRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Taux journalier')),
                ('monthly_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Taux mensuel forfaitaire')),
                ('effective_date', models.DateField(help_text='Date à partir de laquelle ce taux est applicable', verbose_name="Date d'effet")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rates', to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_rates', to='employees.grade')),
            ],
            options={
                'verbose_name': 'Taux de déplacement par grade',
                'verbose_name_plural': 'Taux de déplacement par grade',
                'ordering': ['-effective_date'],
                'indexes': [models.Index(fields=['grade', 'is_active'], name='employees_g_grade_i_910f03_idx'), models.Index(fields=['effective_date'], name='employees_g_effecti_c1fcc1_idx')],
            },
        ),
    ]
