# Generated by Django 5.2.7 on 2025-10-28 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_deploymentforfaitaire_deploymentreal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdreMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de départ')),
                ('end_date', models.DateField(verbose_name='Date de retour')),
                ('location', models.CharField(max_length=255, verbose_name='Lieu de mission')),
                ('purpose', models.TextField(verbose_name='Objet de la mission')),
                ('ordre_document', models.FileField(blank=True, null=True, upload_to='ordres_mission/', verbose_name='Document ordre de mission (preuve)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Demandé le')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Examiné le')),
                ('review_notes', models.TextField(blank=True, verbose_name="Notes d'examen")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ordre de mission',
                'verbose_name_plural': 'Ordres de mission',
                'ordering': ['-start_date', '-requested_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='deploymentreal',
            options={'ordering': ['-start_date', '-created_at'], 'verbose_name': 'Déplacement réel', 'verbose_name_plural': 'Déplacements réels'},
        ),
        migrations.RemoveIndex(
            model_name='deploymentforfaitaire',
            name='employees_d_employe_9ac936_idx',
        ),
        migrations.RemoveIndex(
            model_name='deploymentforfaitaire',
            name='employees_d_month_7c1e78_idx',
        ),
        migrations.RemoveIndex(
            model_name='deploymentforfaitaire',
            name='employees_d_status_1ab8d4_idx',
        ),
        migrations.RemoveIndex(
            model_name='deploymentreal',
            name='employees_d_employe_515db3_idx',
        ),
        migrations.RemoveIndex(
            model_name='deploymentreal',
            name='employees_d_status_10545f_idx',
        ),
        migrations.RemoveField(
            model_name='deploymentforfaitaire',
            name='review_notes',
        ),
        migrations.RemoveField(
            model_name='deploymentforfaitaire',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='deploymentforfaitaire',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='deploymentforfaitaire',
            name='status',
        ),
        migrations.RemoveField(
            model_name='deploymentreal',
            name='requested_at',
        ),
        migrations.RemoveField(
            model_name='deploymentreal',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='deploymentreal',
            name='review_notes',
        ),
        migrations.RemoveField(
            model_name='deploymentreal',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='deploymentreal',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='deploymentreal',
            name='status',
        ),
        migrations.AddField(
            model_name='deploymentreal',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment_real_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='deploymentforfaitaire',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='deploymentforfaitaire',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment_forfaitaire_requests', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='deploymentreal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AddIndex(
            model_name='deploymentforfaitaire',
            index=models.Index(fields=['employee', 'month'], name='employees_d_employe_4af0cc_idx'),
        ),
        migrations.AddIndex(
            model_name='deploymentforfaitaire',
            index=models.Index(fields=['requested_at'], name='employees_d_request_86b60d_idx'),
        ),
        migrations.AddIndex(
            model_name='deploymentreal',
            index=models.Index(fields=['employee'], name='employees_d_employe_a3e85e_idx'),
        ),
        migrations.AddIndex(
            model_name='deploymentreal',
            index=models.Index(fields=['created_at'], name='employees_d_created_24adb4_idx'),
        ),
        migrations.AddField(
            model_name='ordremission',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordres_mission', to='employees.employee', verbose_name='Employé'),
        ),
        migrations.AddField(
            model_name='ordremission',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordre_mission_requests', to=settings.AUTH_USER_MODEL, verbose_name='Demandé par'),
        ),
        migrations.AddField(
            model_name='ordremission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordre_mission_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Examiné par'),
        ),
        migrations.AddIndex(
            model_name='ordremission',
            index=models.Index(fields=['employee', 'status'], name='employees_o_employe_fe045a_idx'),
        ),
        migrations.AddIndex(
            model_name='ordremission',
            index=models.Index(fields=['start_date', 'end_date'], name='employees_o_start_d_e6d7ff_idx'),
        ),
        migrations.AddIndex(
            model_name='ordremission',
            index=models.Index(fields=['status', 'requested_at'], name='employees_o_status_f6dec1_idx'),
        ),
    ]
