# Generated by Django 5.2.7 on 2025-10-28 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_ordremission_alter_deploymentreal_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentforfaitaire',
            name='is_signed',
            field=models.BooleanField(default=False, verbose_name='Signé par la hiérarchie'),
        ),
        migrations.AddField(
            model_name='deploymentforfaitaire',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de signature'),
        ),
        migrations.AddField(
            model_name='deploymentforfaitaire',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment_forfaitaire_signatures', to=settings.AUTH_USER_MODEL, verbose_name='Signé par'),
        ),
        migrations.AddField(
            model_name='deploymentreal',
            name='is_signed',
            field=models.BooleanField(default=False, verbose_name='Signé par la hiérarchie'),
        ),
        migrations.AddField(
            model_name='deploymentreal',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de signature'),
        ),
        migrations.AddField(
            model_name='deploymentreal',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment_real_signatures', to=settings.AUTH_USER_MODEL, verbose_name='Signé par'),
        ),
        migrations.AddField(
            model_name='ordremission',
            name='is_signed',
            field=models.BooleanField(default=False, verbose_name='Signé par la hiérarchie'),
        ),
        migrations.AddField(
            model_name='ordremission',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de signature'),
        ),
        migrations.AddField(
            model_name='ordremission',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordre_mission_signatures', to=settings.AUTH_USER_MODEL, verbose_name='Signé par'),
        ),
    ]
