# Generated by Django 5.2.7 on 2025-10-25 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code like employees.view', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable name', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('module', models.CharField(help_text='Module/app this belongs to (e.g., employees, users)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Function Permission',
                'verbose_name_plural': 'Function Permissions',
                'ordering': ['module', 'code'],
            },
        ),
        migrations.CreateModel(
            name='RoleDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='What this role is for')),
                ('is_system_role', models.BooleanField(default=False, help_text='System roles cannot be deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role_definition', to='auth.group')),
            ],
            options={
                'verbose_name': 'Role Definition',
                'verbose_name_plural': 'Role Definitions',
                'ordering': ['group__name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermissionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_mappings', to='roles.functionpermission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_mappings', to='roles.roledefinition')),
            ],
            options={
                'verbose_name': 'Role Permission Mapping',
                'verbose_name_plural': 'Role Permission Mappings',
                'ordering': ['role', 'function__module', 'function__code'],
                'unique_together': {('role', 'function')},
            },
        ),
    ]
